config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', sessions: "sessions"}
  devise_scope :user do
    post 'users/pre_otp', to: 'sessions#pre_otp'
    # root to: 'users#show'
    authenticated :user do
      root 'users#verify_phone_number', as: :authenticated_root
    end

    unauthenticated do
      root 'sessions#new', as: :unauthenticated_root
    end    
  end
	
  resources :whatspp_messages, only: [:create, :show]
  resources :users, only: [:show, :update, :index] do
  	member do
		  post 'events_count'
		  post 'event_data_by_category_and_minute'
      post 'events_by_category_data'
      get 'verify_phone_number'
      post 'submit_phone_otp'
      get 'change_role_to_admin'
      get 'change_role_to_worker'
		end
  	resources :whatspp_messages, only: [:index]
  end
  resource :two_factor
  # root to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/whatspp_message.rb
class WhatsppMessage < ApplicationRecord
	belongs_to :user
	has_many :events

	def set_events
		Event.set_events_for_a_whatspp_message whatspp_message_id: self.id
	end
end

app/controllers/whatspp_messages_controller.rb
class WhatsppMessagesController < ApplicationController
  before_action :user_logged_in, only: [:index]
  before_action :set_whatspp_message, only: [:show]
  skip_before_action :verify_authenticity_token, only: [:create]

  # GET /whatspp_messages
  # GET /whatspp_messages.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: WhatsppMessagesDatatable.new(view_context,@user) }
    end
  end
  
  # POST /whatspp_messages
  # POST /whatspp_messages.json
  def create
    require 'despamilator'
    if Despamilator.new(params['Body']).score < 0.8
      @user = User.where(phone_number: params['From'].split(':').second).first
      if @user.present? && @user.verified_phone_number
        @whatspp_message = WhatsppMessage.new(user_id: @user.id, data: params['Body'])
        respond_to do |format|
          if @whatspp_message.save
            @whatspp_message.set_events
            format.json { render :show, status: :created, location: @whatspp_message }
          else
            format.json { render json: @whatspp_message.errors, status: :unprocessable_entity }
          end
        end
      else
        respond_to do |format|
          format.json { render json: @whatspp_message.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.json { render json: {}, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/whatspp_messages_helper.rb
module WhatsppMessagesHelper
end

app/views/whatspp_messages/index.html.erb
<%= stylesheet_link_tag 'dataTables.bootstrap4.css' %>
<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-table"></i>
    Logs</div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered display" id="dataTable" width="100%" cellspacing="0"data-source="<%= user_whatspp_messages_path(user_id: @user.id, format: "json") %>">
        <thead>
          <tr>
            <th>Time</th>
            <% if @user.admin? %>
              <th>User</th>
              <th>Phone Number</th>
            <% end %>
            <th>Event Category</th>
            <th>Message</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
        <tfoot>
          <tr>
            <th>Time</th>
            <% if @user.admin? %>
              <th>User</th>
              <th>Phone Number</th>
            <% end %>
            <th>Event Category</th>
            <th>Message</th>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
  <div class="card-footer small text-muted" id="last_time_data_table_updated"></div>
</div>

<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" integrity="sha384-rgWRqC0OFPisxlUvl332tiM/qmaNxnlY46eksSZD84t+s2vZlqGeHrncwIRX7CGp" crossorigin="anonymous"></script>

<%= javascript_include_tag 'datatables-demo' %>

app/views/whatspp_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @whatspp_message.data %>
</p>

<p>
  <strong>User:</strong>
  <%= @whatspp_message.user_id %>
</p>

<p>
  <strong>Spam:</strong>
  <%= @whatspp_message.spam %>
</p>

<%= link_to 'Edit', edit_whatspp_message_path(@whatspp_message) %> |
<%= link_to 'Back', whatspp_messages_path %>