config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', sessions: "sessions"}
  devise_scope :user do
    post 'users/pre_otp', to: 'sessions#pre_otp'
    # root to: 'users#show'
    authenticated :user do
      root 'users#verify_phone_number', as: :authenticated_root
    end

    unauthenticated do
      root 'sessions#new', as: :unauthenticated_root
    end    
  end
	
  resources :whatspp_messages, only: [:create, :show]
  resources :users, only: [:show, :update, :index] do
  	member do
		  post 'events_count'
		  post 'event_data_by_category_and_minute'
      post 'events_by_category_data'
      get 'verify_phone_number'
      post 'submit_phone_otp'
      get 'change_role_to_admin'
      get 'change_role_to_worker'
		end
  	resources :whatspp_messages, only: [:index]
  end
  resource :two_factor
  # root to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  devise :two_factor_authenticatable,
  			 :two_factor_backupable,
         :otp_secret_encryption_key => Rails.application.secrets.otp_key

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
	has_many :whatspp_messages
	has_many :events, through: :whatspp_messages
	enum role: {
		'admin': 0,
		'worker': 1
	}

	def otp_qr_code
    issuer = 'Khushi'
    label = "#{issuer}:#{email}"
    qrcode = RQRCode::QRCode.new(otp_provisioning_uri(label, issuer: issuer))
    qrcode.as_svg(module_size: 4)
  end

  def otp_backup_codes
    super_return_value = super
    JSON.parse(super_return_value) if super_return_value.present?
  end	

  def generate_new_mobile_otp
    otp = rand(10**6)
    self.sms_otp = otp
    self.save
  end

  def send_otp_to_user_mobile
    require 'twilio-ruby'

    # # Your Account Sid and Auth Token from twilio.com/console
    account_sid = Rails.application.secrets.twilio_account_sid
    auth_token = Rails.application.secrets.twilio_auth_token
    @client = Twilio::REST::Client.new(account_sid, auth_token)

    # message = @client.messages
    #   .create(
    #      body: "OTP #{self.sms_otp}",
    #      from: '+13073177442', 
    #      # status_callback: 'http://requestb.in/1234abcd',
    #      to: self.phone_number.to_s
    #    )

    @client = Twilio::REST::Client.new(account_sid, auth_token)

    message = @client.messages.create(
                                 body: "OTP #{self.sms_otp}",
                                 from: 'whatsapp:+441618507453',
                                 to: "whatsapp:#{self.phone_number.to_s}"
                               )

    puts message.sid

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_logged_in
  before_action :load_whatspp_message_ids, except: [:verify_phone_number, :submit_phone_otp, :index, :change_role_to_worker, :change_role_to_admin]
  before_action :check_if_admin, only: [:index, :change_role_to_worker, :change_role_to_admin]
  # before_action :verified_phone_number?, only: [:show]
  layout :resolve_layout

  def index
    @users = User.all
  end
  # GET /users/1
  # GET /users/1.json
  def show
    @event_data_by_category_and_minute = Event.where(whatspp_message_id: @whatspp_message_ids).group(:category).group_by_minute(:created_at).count
    @event_data_by_category = Event.where(whatspp_message_id: @whatspp_message_ids).group(:category).count
  end

  def events_count
    if params['category'].present?
      event_data = Event.where(category: params['category']).where(whatspp_message_id: @whatspp_message_ids).group_by_minute(:created_at).count.count
    else
      event_data = Event.where(whatspp_message_id: @whatspp_message_ids).group(:category).group_by_minute(:created_at).count.count
    end
    respond_to do |format|
      format.json { render json: event_data }
    end    
  end

  def event_data_by_category_and_minute
    if params['category'].present?
      event_data_by_category_and_minute = Event.where(category: params['category']).where(whatspp_message_id: @whatspp_message_ids).group_by_minute(:created_at).count
    else
      event_data_by_category_and_minute = Event.where(whatspp_message_id: @whatspp_message_ids).group(:category).group_by_minute(:created_at).count
    end
    respond_to do |format|
      format.json { render json: JSON.parse(event_data_by_category_and_minute.chart_json) }
    end
  end

  def events_by_category_data
    if params['category'].present?
      event_data_by_category = Event.where(category: params['category']).where(whatspp_message_id: @whatspp_message_ids).group(:category).count
    else
      event_data_by_category = Event.where(whatspp_message_id: @whatspp_message_ids).group(:category).count
    end
    respond_to do |format|
      format.json { render json: event_data_by_category }
    end
  end

  # GET /users/new
  # def new
  #   @user = User.new
  # end

  # GET /users/1/edit
  # def edit
  # end

  # # POST /users
  # # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        # format.json { redire :index, status: :ok, location: @user }
      else
        format.html { redirect_to action: 'edit' }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def verify_phone_number
    if @user.verified_phone_number
      redirect_to @user
    else
      @user.generate_new_mobile_otp
      @user.send_otp_to_user_mobile
    end
  end

  def submit_phone_otp
    if params['otp'].to_i == @user.sms_otp
      @user.verified_phone_number = 1
      @user.save
      redirect_to @user, notice: 'Phone Verified'
    else
      redirect_to verify_phone_number_user_path(id: @user.id)
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  def change_role_to_admin
    user = User.find(params['id'])
    user.number_of_admin_users_requested = 0
    user.role = 0
    user.save
    redirect_to users_url
  end

  def change_role_to_worker
    user = User.find(params['id'])
    user.number_of_admin_users_requested += 1
    if user.number_of_admin_users_requested > (0.75 * (User.where(role: 0).count-1))
      user.role = 1
    end
    user.save
    redirect_to users_url
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :second_name, :password, :password_confirmation, :otp)
    end

    def resolve_layout
      case action_name
      when 'verify_phone_number'
        'devise'
      else
        'application'
      end
    end

    def load_whatspp_message_ids
      whatspp_messages = WhatsppMessage.none
      if @user.admin?
        whatspp_messages = WhatsppMessage.all
        whatspp_messages = whatspp_messages.where(user_id: params['user']) if params['user'].present?
      else
        whatspp_messages = @user.whatspp_messages
      end      
      whatspp_messages = whatspp_messages.where('created_at > ?', Time.parse(params['start_date'])) if params['start_date'].present?
      whatspp_messages = whatspp_messages.where('created_at < ?', Time.parse(params['end_date'])) if params['end_date'].present?
      # @whatspp_messages = @whatspp_messages.where(user_id: params['user') if params['user']
      # if params['category'].present?
      #   @whatspp_message_ids = Event.where(category: params['category']).where(whatspp_message_id: whatspp_messages.ids).pluck(:whatspp_message_id)
      # end
      @whatspp_message_ids = whatspp_messages.pluck(:id)
    end

    def check_if_admin
      redirect_to @user unless @user.admin?
    end

    # def verified_phone_number?
    #   redirect_to verify_phone_number_user_path(id: @user.id) unless @user.verified_phone_number
    # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :second_name %>
    <%= form.text_field :second_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%#= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="table-responsive">
  <table class="table table-sm table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Role</th>
        <th scope="col">Phone Number</th>
        <!-- <th scope="col" colspan="3"></th> -->
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody >
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.second_name %></td>
          <td><%= user.email %></td>
          <td><%= user.role %></td>
          <td><%= user.phone_number %></td>
          <!-- <td><%#= link_to 'Show', user %></td> -->
          <td>
            <% if user.admin? %>
              <%= link_to 'Dismiss as Admin', change_role_to_worker_user_path(user) %>
            <% else %>
              <%= link_to 'Make Admin', change_role_to_admin_user_path(user) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%#= @user.first_name %>
</p>

<p>
  <strong>Second name:</strong>
  <%#= @user.second_name %>
</p>

<p>
  <strong>Email:</strong>
  <%#= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%#= @user.role %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%#= @user.phone_number %>
</p>


<%#= link_to 'Edit', edit_user_path(@user) %> |
<%#= link_to 'Back', users_path %>
 -->

<%#= line_chart @events.map { |event|
    { name: event.category, data: event.group_by_minute(:created_at, time_zone: "New Delhi").count }
} %>

<%#= line_chart User.group_by_minute(:created_at).count %>

<%# event_data = Event.group(:category).group_by_minute(:created_at).count %>
<%#= event_data %>

<div id="users_show_page">
  
  <div class="form-inline" action="#">
    <strong>Events Activity Time Line Graph</strong>&nbsp;&nbsp;&nbsp;
    <div class="form-group">
      <input type="text" class="form-control" id="start_date" placeholder="Start date">
      <!-- <input size="16" type="text" value="2012-06-15 14:45" id="start_date" readonly class="form_datetime"> -->
    </div>&nbsp;&nbsp;
    <div class="form-group">
      <input type="text" class="form-control" id="end_date" placeholder="End date">
    </div>&nbsp;&nbsp;
    <div class="form-group">
      <!-- <input type="text" class="form-control" id="category" placeholder="Category"> -->
      <%#= select_tag 'Category', options_for_select(Event.categories.to_a), {class: 'form-control'} %>
       <select class="form-control" id="category" placeholder="category">
          <!-- <option value=""></option> -->
          <option value="" selected>Select Category</option>
        <% Event.categories.each do |cat, val| %>
          <option value="<%=val%>"><%= cat %></option>
        <% end %>
      </select> 
    </div>&nbsp;&nbsp;
    <% if @user.admin? %>
      <div class="form-group">
        <!-- <input type="text" class="form-control" id="user" placeholder="User"> -->
        <%= select_tag :user, options_for_select(User.all.pluck(:first_name, :id)), {class: 'form-group form-control', include_blank: true} %>
      </div>&nbsp;&nbsp;
    <% end %>
    <button type="submit" class="btn btn-default" id="refresh_data">Refresh Data</button>
  </div> 
  <%= line_chart @event_data_by_category_and_minute, id: 'event_line_chart' %>
  <p id="user_events_path" data-user-events-path=<%= event_data_by_category_and_minute_user_path(id: @user.id) %> data-user-events-count=<%= @event_data_by_category_and_minute.count %> data-user-events-count-path=<%= events_count_user_path(id: @user.id) %> data-user-events-category-path=<%= events_by_category_data_user_path(id: @user.id)%> data-start-date="" data-end-date="" data-user-id="" data-category-id="" ></p>
  
  <strong>Events Activity Table</strong>
  <table class="table table-sm">
    <thead class="thead-light">
      <tr>
        <th scope="col">S.No</th>
        <th scope="col">Category</th>
        <th scope="col">Count</th>
      </tr>
    </thead>
    <tbody>
      <% @event_data_by_category.each_with_index do |(category,count),index| %>
        <tr>
          <th scope="row"><%= index+1 %></th>
          <td><%= category %></td>
          <td id="<%= category %>_count"><%= count %></td>
        </tr>
      <% end %>
      <% outer_index = @event_data_by_category.count %>
      <% (Event.categories.keys - @event_data_by_category.keys).each_with_index do |cat,index| %>
        <tr>
          <th scope="row"><%= outer_index+1+index %></th>
          <td><%= cat %></td>
          <td id="<%= cat %>_count">0</td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/verify_phone_number.html.erb
<div class="container">
  <div class="card card-login mx-auto mt-5">
    <div class="card-header">An OTP SMS is sent to Your phone number, Please enter the OTP below</div>
    <div class="card-body">
      <%#= form_with(model: @user, :url => {:controller => "users", :action => "submit_phone_otp", :method => 'POST'}, local: true) do |f| %>
      <%= form_tag(submit_phone_otp_user_path(id: @user.id) , method: 'post')%>
			  <% if @user.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

			      <ul>
			      <% @user.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			      </ul>
			    </div>
			  <% end %>
        <div class="form-group">
          <div class="form-label-group">
            <%#= f.text_field :sms_otp, autofocus: true, class: 'form-control',placeholder: 'OTP' %>
            <%= text_field_tag 'otp',nil, { autofocus: true, class: 'form-control', placeholder: 'OTP'} %>
            <label for="otp">SMS OTP</label>
          </div>
        </div>
        <%#= f.submit "Verify Mobile Number", class: 'btn btn-primary btn-block' %>
        <% submit_tag "Verify Mobile Number", class: 'btn btn-primary btn-block' %>
      <%# end %>
    </div>
  </div>
</div>