config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', sessions: "sessions"}
  devise_scope :user do
    post 'users/pre_otp', to: 'sessions#pre_otp'
    # root to: 'users#show'
    authenticated :user do
      root 'users#verify_phone_number', as: :authenticated_root
    end

    unauthenticated do
      root 'sessions#new', as: :unauthenticated_root
    end    
  end
	
  resources :whatspp_messages, only: [:create, :show]
  resources :users, only: [:show, :update, :index] do
  	member do
		  post 'events_count'
		  post 'event_data_by_category_and_minute'
      post 'events_by_category_data'
      get 'verify_phone_number'
      post 'submit_phone_otp'
      get 'change_role_to_admin'
      get 'change_role_to_worker'
		end
  	resources :whatspp_messages, only: [:index]
  end
  resource :two_factor
  # root to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Khushi</title>
    <!-- Required meta tags for bootstrap-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//www.google.com/jsapi" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" integrity="sha384-O1hPCzrpXngZMErIjr+H0eOvTf1GKeN4n8CAAgeGgNT8SmQot8u0Zf7V9ipByhSi" crossorigin="anonymous"> -->
    <%= stylesheet_link_tag 'bootstrap-datetimepicker' %>
    <%= stylesheet_link_tag params[:controller] unless params[:controller].include? 'devise'%>
  </head>
  <% website_name = 'Khushi' %>
  <body id="page-top">
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
      <a class="navbar-brand mr-1" href="index.html"><%= website_name %></a>

      <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
      </button>

      <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      </div>
      

      <!-- Navbar -->
      <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell fa-fw"></i>
            <span class="badge badge-danger">9+</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
            <a class="dropdown-item" href="#">BLAH</a>
            <a class="dropdown-item" href="#">BLAH</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">BLAH</a>
          </div>
        </li>
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-envelope fa-fw"></i>
            <span class="badge badge-danger">7</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
            <a class="dropdown-item" href="#">BLAH</a>
            <a class="dropdown-item" href="#">BLAH</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">BLAH</a>
          </div>
        </li>
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <!-- <a class="dropdown-item" href="#">Settings</a> -->
            <%= link_to "Settings", edit_user_registration_path(id: @user.id), {class: 'dropdown-item'} %>
            <%= link_to "Activity Log", user_whatspp_messages_path(user_id: @user.id), {class: 'dropdown-item'} %>
            <!-- <a class="dropdown-item" href="#">Activity Log</a> -->
            <!-- user_whatspp_messages -->
            <div class="dropdown-divider"></div>
            <%#= link_to "Logout", destroy_user_session_path, {method: :delete, class: 'dropdown-item', data: {toggle: 'modal', target: '#logoutModal'}} %>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
          </div>
        </li>
      </ul>
    </nav>

    <div id="wrapper">
      <!-- Sidebar -->
      <ul class="sidebar navbar-nav" id="sidebar_navbar">
        <li class="nav-item active">
          <a class="nav-link" id="dashboard" href=<%= user_path(@user) %> >
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Summary</span>
          </a>

        </li>
        <li class="nav-item">
          <a class="nav-link" id="calendar" href="<%= user_whatspp_messages_path(user_id: @user.id) %>">
            <i class="fas fa-signature"></i>
            <span>Logs</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="user_path" href= <%= edit_user_registration_path(user_id: @user.id) %>>
            <%#= link_to 'Edit profile', edit_user_registration_path %>
            <i class="fas fa-user"></i>
            
            <span><%= @user.first_name %></span></a>
        </li>
        <% if @user.admin? %>
          <li class="nav-item">
            <a class="nav-link" id="users_path" href= <%= users_path %>>
              <%#= link_to 'Edit profile', edit_user_registration_path %>
              <i class="fas fa-users"></i>
              
              <span>Users</span></a>
          </li>
        <% end %>
      </ul>

      <div id="content-wrapper">

        <div class="container-fluid">
          <% if notice.present? %>
            <div class="alert alert-success notice" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <strong><%= notice %></strong>
            </div>
          <% end %>
          <% if alert.present? %>
            <div class="alert alert-danger notice" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <strong><%= alert %></strong>
            </div>
          <% end %>
          <%= yield %>
        </div>
        <!-- /.container-fluid -->

        <!-- Sticky Footer -->
        <footer class="sticky-footer">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright © <%= website_name %> 2018</span>
            </div>
          </div>
        </footer>

      </div>
      <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <%= link_to "Logout", destroy_user_session_path, {method: :delete, class: 'btn btn-primary'} %>
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js" integrity="sha384-leGYpHE9Tc4N9OwRd98xg6YFpB9shlc/RkilpFi0ljr3QD4tFoFptZvgnnzzwG4Q" crossorigin="anonymous"></script> 

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" integrity="sha384-rgWRqC0OFPisxlUvl332tiM/qmaNxnlY46eksSZD84t+s2vZlqGeHrncwIRX7CGp" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'dataTables.bootstrap4.js' %>
    <%= javascript_include_tag "sb-admin.js"%>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js" integrity="sha384-eRwUWQDbnWMRrNpCKFsqmkfL7PMM8a4uUw5AvjTuLRoYFfozRz7g9BS696LvdNrE" crossorigin="anonymous"></script> -->
    <%= javascript_include_tag 'bootstrap-datetimepicker' %>
    <%= javascript_include_tag params[:controller] unless params[:controller].include? 'devise'%>
  </body>

</html>

app/views/layouts/devise.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>Khushi</title>
    <!-- Required meta tags for bootstrap-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="bg-dark">
      <% if notice.present? %>
        <div class="alert alert-success notice" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong><%= notice %></strong>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="alert alert-danger notice" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong><%= alert %></strong>
        </div>
      <% end %>
      <%= yield %>
      <script type="text/javascript">
        window.setTimeout((function() {
          $('.alert').fadeTo(500, 0).slideUp(500, function() {
            $(this).remove();
          });
        }), 4000);
      </script>
  </body>
</html>